accent = "#a277ff"
cursor = "#a277ff"
foreground = "#edecee"
background = "#15141b"
selection_foreground = "#edecee"
selection_background = "#29263c"

color0 = "#110f18"
color1 = "#ff6767"
color2 = "#61ffca"
color3 = "#ffca85"
color4 = "#a277ff"
color5 = "#a277ff"
color6 = "#61ffca"
color7 = "#edecee"
color8 = "#4d4d4d"
color9 = "#ff6767"
color10 = "#61ffca"
color11 = "#ffca85"
color12 = "#a277ff"
color13 = "#a277ff"
color14 = "#61ffca"
color15 = "#edecee"
